#!/bin/bash -e
name=$(./software-info.pl software-internal-name)
bits=32
if [[ "$1" == "64" ]]; then
  bits=64
fi
if [[ "$PROFILE_MATS" == "no" ]]; then
  launch="./scheme$bits -q repl.ss run-mats.ss"
else
  rm -f "../data/server.profile"
  launch="./scheme$bits -q replp.ss run-mats.ss"
fi

if [[ "$OUTDIR" != "" ]]; then
    outdir=$OUTDIR
else
    outdir="."
fi

make clean

rm -f "../data/TestLog.db3"

# Swish
source swish/run-mats

# finish up
$launch <<EOF
(html-report "$outdir" "$outdir/mat-report.html")
(console-summary "$outdir")
EOF

if [[ "$PROFILE_MATS" != "no" ]]; then
  ./dump-profile $bits
fi
