#!/bin/bash -e
bits=32
if [[ "$1" == "64" ]]; then bits=64; fi
if [[ "$OUTDIR" != "" ]]; then
    outdir=$OUTDIR
else
    outdir="."
fi

make clean

export BUILD=Hooks
make -s -e exe$bits

./scheme$bits -q swish/osi.ms <<EOF
(go2 "$outdir")
EOF
